### ISSUE TITLE
[Bug] データベースの初期化がうまくできてない

### ISSUE THREAD

**Issue by huequica** [HIKAKINSymmetry/nodeBot#8]
```bash
データべース内部に何も入っていません 初期化作業を開始します
(node:22968) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'url' of undefined
    at /home/huequica/Github.com/HIKAKINSymmetry/nodeBot/src/modules/checkYoutube.ts:50:77
    at Array.map (<anonymous>)
    at pickMoviesDetail (/home/huequica/Github.com/HIKAKINSymmetry/nodeBot/src/modules/checkYoutube.ts:46:16)
    at /home/huequica/Github.com/HIKAKINSymmetry/nodeBot/src/modules/checkYoutube.ts:84:13
    at Array.map (<anonymous>)
    at /home/huequica/Github.com/HIKAKINSymmetry/nodeBot/src/modules/checkYoutube.ts:82:49
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(node:22968) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 51)
```

**Comment by huequica** [comment]
YoutubeのAPIから帰ってくるデータの中にサムネイルが `high` までしかないものを確認した、なんだよそれ…
```js
{
  kind: 'youtube#playlistItem',
  etag: '********',
  id: '****************',
  snippet: {
    publishedAt: '2017-02-28T14:00:43Z',
    channelId: '********',
    title: 'ひっそり生配信',
    description: '........',
    thumbnails: { default: [Object], medium: [Object], high: [Object] },
    channelTitle: 'HikakinBlog',
    playlistId: 'UUQMoeRP9SDaFipXDBIp3pFA',
    position: 5,
    resourceId: { kind: 'youtube#video', videoId: '********' },
    videoOwnerChannelTitle: 'HikakinBlog',
    videoOwnerChannelId: '********'
  }
}
```
